# Generated by Django 5.2.8 on 2025-11-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Software name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('logo_url', models.TextField(blank=True, help_text='URL to the software logo')),
                ('repository_url', models.TextField(blank=True, help_text='URL to the source code repository')),
                ('website_url', models.TextField(blank=True, help_text='URL to the software website')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published')], default='draft', help_text='Publication state', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_at', models.DateTimeField(blank=True, help_text='When the software was featured', null=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorization', related_name='softwares', to='categories.tag')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
                'ordering': ['-created_at'],
            },
        ),
    ]
