# Generated by Django 5.2.8 on 2025-11-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('overview', 'Overview'), ('use_case', 'Use Case'), ('features', 'Features')], help_text='Type of content block', max_length=50)),
                ('locale', models.CharField(help_text="Language code (e.g., 'en', 'fr', 'de')", max_length=10)),
                ('content', models.TextField(help_text='Markdown content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='categories.software')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'ordering': ['software', 'kind', 'locale'],
                'unique_together': {('software', 'kind', 'locale')},
            },
        ),
    ]
