# Generated by Django 5.2.8 on 2025-12-01 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Analysis score (1.00 to 5.00)', max_digits=5)),
                ('is_published', models.BooleanField(default=False, help_text='Whether the result is published')),
                ('is_manual', models.BooleanField(default=False, help_text='TRUE if manually entered/corrected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='categories.field')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='categories.software')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['software', 'field'], name='categories__softwar_aa8af8_idx'), models.Index(fields=['is_published'], name='categories__is_publ_cebd84_idx')],
            },
        ),
    ]
