# Generated by Django 5.2.8 on 2026-01-07 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_analysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the metric', max_length=100)),
                ('weight', models.IntegerField(default=1, help_text='Weight for aggregating multiple metrics')),
                ('collection_enabled', models.BooleanField(default=True, help_text='Whether automated collection is enabled')),
                ('score_mapping_config', models.JSONField(blank=True, help_text='JSON config for mapping values to scores', null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='categories.field')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'ordering': ['field', 'weight', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MetricTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(help_text="Language code (e.g., 'en', 'fr', 'de')", max_length=10)),
                ('name', models.CharField(help_text='Metric name in this language', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Metric description in this language')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.metric')),
            ],
            options={
                'verbose_name': 'Metric Translation',
                'verbose_name_plural': 'Metric Translations',
                'ordering': ['locale'],
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, help_text='Metric value (e.g., 45000 for GitHub stars, 0.85 for percentages)', max_digits=20)),
                ('collected_at', models.DateTimeField(auto_now_add=True, help_text='When this value was collected')),
                ('source', models.CharField(blank=True, help_text="Source of the data (e.g., 'GitHub API')", max_length=255)),
                ('is_valid', models.BooleanField(default=True, help_text='Whether this value is valid')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='categories.metric')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='categories.software')),
            ],
            options={
                'verbose_name': 'Metric Value',
                'verbose_name_plural': 'Metric Values',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['field', 'collection_enabled'], name='categories__field_i_8b5864_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('field', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='metrictranslation',
            unique_together={('metric', 'locale')},
        ),
        migrations.AddIndex(
            model_name='metricvalue',
            index=models.Index(fields=['metric', 'software', '-collected_at'], name='categories__metric__4fde3e_idx'),
        ),
        migrations.AddIndex(
            model_name='metricvalue',
            index=models.Index(fields=['software', '-collected_at'], name='categories__softwar_d41172_idx'),
        ),
        migrations.AddIndex(
            model_name='metricvalue',
            index=models.Index(fields=['is_valid'], name='categories__is_vali_3b0ce8_idx'),
        ),
    ]
