# Generated by Django 5.2.8 on 2026-01-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_metric_metrictranslation_metricvalue_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metricvalue',
            name='categories__is_vali_3b0ce8_idx',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='score_mapping_config',
        ),
        migrations.RemoveField(
            model_name='metricvalue',
            name='is_valid',
        ),
    ]
