# Generated by Django 5.2.8 on 2026-01-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_remove_metricvalue_categories__is_vali_3b0ce8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='last_metrics_update_at',
            field=models.DateTimeField(blank=True, help_text='When metrics were last updated for this software', null=True),
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(condition=models.Q(('state', 'published')), fields=['state', 'last_metrics_update_at'], name='idx_soft_last_metrics_upd'),
        ),
    ]
