# Generated by Django 5.2.8 on 2026-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_software_last_metrics_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('error', 'Error')], default='draft', help_text='Publication state', max_length=50),
        ),
    ]
