# Generated by Django 5.2.8 on 2026-02-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_add_software_error_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtranslation',
            name='description',
            field=models.TextField(blank=True, help_text='Field description in this language'),
        ),
    ]
