# Generated by Django 5.2.8 on 2026-02-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_fieldtranslation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(help_text="Language code (e.g., 'en', 'fr', 'de')", max_length=10)),
                ('content', models.TextField(help_text='Markdown content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='categories.tag')),
            ],
            options={
                'verbose_name': 'Tag Opinion',
                'verbose_name_plural': 'Tag Opinions',
                'ordering': ['tag', 'locale'],
                'unique_together': {('tag', 'locale')},
            },
        ),
    ]
