# Generated by Django 5.2.8 on 2026-03-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_tagopinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostFeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10)),
                ('general_comment', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_feedback_submissions', to='categories.software')),
            ],
            options={
                'verbose_name': 'Cost Feedback Submission',
                'verbose_name_plural': 'Cost Feedback Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostFeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_feedback_entries', to='categories.field')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='categories.costfeedbacksubmission')),
            ],
            options={
                'verbose_name': 'Cost Feedback Entry',
                'verbose_name_plural': 'Cost Feedback Entries',
                'unique_together': {('submission', 'field')},
            },
        ),
    ]
