# Generated by Django 5.2.8 on 2026-03-18 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_cost_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costfeedbackentry',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
