# Generated by Django 5.2.8 on 2025-11-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the field', max_length=100)),
                ('weight', models.IntegerField(default=1, help_text='Weight for sorting fields')),
                ('analysis_periodicity_days', models.IntegerField(blank=True, help_text='Analysis periodicity in days (e.g., 7 for weekly, 30 for monthly, NULL for manual only)', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='categories.category')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['category', 'weight', 'id'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FieldTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(help_text="Language code (e.g., 'en', 'fr', 'de')", max_length=10)),
                ('name', models.CharField(help_text='Field name in this language', max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.field')),
            ],
            options={
                'verbose_name': 'Field Translation',
                'verbose_name_plural': 'Field Translations',
                'ordering': ['locale'],
                'unique_together': {('field', 'locale')},
            },
        ),
    ]
